# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.TextField()),
                ('text', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to=b'')),
            ],
        ),
    ]
