# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0004_auto_20171012_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='log',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
