# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0006_auto_20171012_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
