# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0007_watch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='watch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='secret.Watch'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watches', to='secret.Piece'),
        ),
    ]
