# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 13:15
from __future__ import unicode_literals

import cloud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_userfile_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='folder',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='user_file',
            field=models.FileField(null=True, upload_to=cloud.models.user_file_path),
        ),
    ]
